Repository christianahvilla/surveys-cahv, pull requests merged in 2023-08, with the labels that each got.

#37 FEAT 19 [Modal] add all the logic for the global modal
  src/App.tsx
  src/components/app/common-modal/helper.tsx
  src/components/app/common-modal/modal.element.tsx
  src/components/app/common-notification/constants.tsx
  src/hooks/useModal.tsx
  src/utils/ModalProvider.tsx
Labels: QA approved, approved

#39 [FIX]: Complete Create Survey
  src/pages/clients/list/loader.ts
  src/pages/surveys/create/create-action.ts
  src/pages/surveys/create/surveys-create.element.tsx
  src/pages/surveys/edit/edit-action.ts
  src/pages/surveys/edit/loader.ts
  src/pages/surveys/edit/surveys-edit.element.tsx
  src/pages/surveys/edit/types.ts
  src/pages/users/create/create-action.ts
Labels: ready for review

#42 [FIX]: Fix creating question action
  src/hooks/useGetSurveys.tsx
  src/hooks/useSaveQuestion.tsx
  src/pages/questions/create/helpers.tsx
  src/pages/questions/create/questions-create.element.tsx
  src/pages/questions/list/constants.tsx
  src/types/selects/survey-object.type.ts
Labels: ready for review

#44 [FIX]: Enable editing a question
  index.html
  src/components/app/error/error.element.tsx
  src/hooks/useEditQuestion.tsx
  src/hooks/useGetQuestionById.tsx
  src/hooks/useSaveQuestion.tsx
  src/pages/questions/create/questions-create.element.tsx
  src/pages/questions/edit/questions-edit.element.tsx
  src/pages/questions/helpers.tsx
  src/pages/questions/list/constants.tsx
  src/pages/questions/list/questions-list.element.tsx
  src/types/questions/questions-action-objects.ts
Labels: ready for review

#46 [FEAT]: Delete unnecessary delete actions
  src/pages/clients/list/clients-list.element.tsx
  src/pages/clients/list/constants.tsx
  src/pages/questions/list/constants.tsx
Labels: ready for review

#52 48 feat
  src/clean-core/entity/requirement/index.ts
  src/clean-core/entity/requirement/requirement.dto.ts
  src/components/app/error/error.element.tsx
  src/pages/requirements/create/create-action.ts
  src/pages/requirements/create/loader.ts
  src/pages/requirements/create/requirement-create-error.element.tsx
  src/pages/requirements/create/requirements-create.element.tsx
  src/pages/requirements/create/routes.tsx
  src/pages/requirements/create/urls.ts
  src/pages/requirements/edit/edit-action.ts
  src/pages/requirements/edit/helpers.tsx
  src/pages/requirements/edit/loader.ts
  src/pages/requirements/edit/requirements-edit-error.element.tsx
  src/pages/requirements/edit/requirements-edit.element.tsx
  src/pages/requirements/edit/routes.tsx
  src/pages/requirements/edit/urls.ts
  src/pages/requirements/helpers.tsx
  src/pages/requirements/routes.tsx
  src/types/requirements/requirement-edit-object.ts
  src/types/requirements/requirements-surveys-list-object.ts
Labels: ready for review

#53 [FEAT-38]: Implement requirements for surveys
  src/clean-core/entity/surveys/surveys.dto.ts
  src/hooks/useGetQuestions.tsx
  src/pages/account/account.element.tsx
  src/pages/clients/create/clients-create.element.tsx
  src/pages/clients/edit/clients-edit.element.tsx
  src/pages/clients/list/constants.tsx
  src/pages/questions/create/questions-create.element.tsx
  src/pages/questions/edit/questions-edit.element.tsx
  src/pages/questions/list/constants.tsx
  src/pages/questions/list/questions-list.element.tsx
  src/pages/surveyed/list/loader.ts
  src/pages/surveyed/list/surveyed-list.element.tsx
  src/pages/surveys/create/create-action.ts
  src/pages/surveys/create/helpers.tsx
  src/pages/surveys/create/loader.ts
  src/pages/surveys/create/surveys-create.element.tsx
  src/pages/surveys/edit/edit-action.ts
  src/pages/surveys/edit/helpers.tsx
  src/pages/surveys/edit/loader.ts
  src/pages/surveys/edit/surveys-edit.element.tsx
  src/pages/surveys/edit/types.ts
  src/pages/surveys/helpers.tsx
  src/pages/surveys/list/constants.tsx
  src/pages/surveys/list/loader.ts
  src/pages/surveys/list/surveys-list.element.tsx
  src/pages/users/create/users-create.element.tsx
  src/pages/users/edit/users-edit.element.tsx
  src/pages/users/list/constants.tsx
  src/types/clients/clients-list-object.ts
  src/types/questions/questions-list-object.ts
  src/types/selects/clients-object.type.ts
  src/types/surveyed/surveyed-list-object.ts
  src/types/surveys/surveys-list-object.ts
  src/types/users/users-list-object.ts
Labels: ready for review

#57 [FEAT]: Impmenent next-ui
  .env
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/Icons/ArrowBackIcon.tsx
  src/components/Icons/EyeFilledIcon.tsx
  src/components/Icons/EyeSlashFilledIcon.tsx
  src/components/Icons/FocusIcon.tsx
  src/components/Icons/UserIcon.tsx
  src/components/Icons/types.ts
  src/components/app/navbar/app-navbar.component.tsx
  src/components/app/navbar/components/app-navbar-brand.component.tsx
  src/components/app/navbar/components/app-navbar-menu.component.tsx
  src/components/app/navbar/components/app-navbar-toggle.component.tsx
  src/components/app/navbar/components/app-navbar-user.component.tsx
  src/components/app/navbar/constants.ts
  src/components/app/navbar/helpers.tsx
  src/components/app/navbar/style.css
  src/components/app/navbar/types.ts
  src/components/app/table/app-table.component.tsx
  src/components/app/title-actions/app-title-page.component.tsx
  src/components/app/title-page/app-title-page.component.tsx
  src/components/buttons/add-button/app-add-button.component.tsx
  src/components/buttons/add-button/constants.ts
  src/components/buttons/back-button/app-back-button.component.tsx
  src/components/buttons/form-buttons/form-buttons.component.tsx
  src/components/containers/page-container.component.tsx
  src/components/containers/parent-container.component.tsx
  src/components/containers/types.ts
  src/components/inputs/dropdown/helpers.tsx
  src/components/inputs/dropdown/input-dropdown.component.tsx
  src/components/inputs/dropdown/types.ts
  src/components/inputs/password/input-password.component.tsx
  src/constants.ts
  src/pages/login/assets/Comprobante de Pago.pdf
  src/pages/login/assets/Invoice_1401519361.pdf
  src/pages/login/assets/login_background.jpg
  src/pages/login/assets/login_background2.jpg
  src/pages/login/constants.ts
  src/pages/login/login.element.tsx
  src/pages/login/style.css
  src/pages/users/constants.ts
  src/pages/users/create/constants.ts
  src/pages/users/create/create-action.ts
  src/pages/users/create/users-create.element.tsx
  src/pages/users/edit/constants.ts
  src/pages/users/edit/users-edit.element.tsx
  src/pages/users/list/constants.tsx
  src/pages/users/list/users-list.element.tsx
  src/pages/utils/RequireAuth.tsx
  src/tailwind.css
  src/utils/helpers.tsx
  tailwind.config.js
  yarn.lock
Labels: ready for review

#68 All buttons has been disabled
  src/components/app/navbar/constants.ts
  src/index.css
  src/pages/clients/list/constants.tsx
  src/pages/surveys/list/constants.tsx
  src/pages/users/list/constants.tsx
Labels: approved

#58 [30-SPIKE]: Complete Options
  src/App.tsx
  src/clean-core/entity/options/index.ts
  src/clean-core/entity/options/options.dto.ts
  src/components/Icons/CloudIcon.tsx
  src/components/Icons/ImageIcon.tsx
  src/components/Icons/XIcon.tsx
  src/components/app/navbar/constants.ts
  src/components/app/sidenav/sidenav-element.component.tsx
  src/components/containers/page-container.component.tsx
  src/components/inputs/dropdown/helpers.tsx
  src/components/inputs/dropdown/input-dropdown.component.tsx
  src/components/inputs/dropdown/types.ts
  src/components/inputs/file/input-file.component.tsx
  src/constants.ts
  src/pages/login/assets/Comprobante de Pago.pdf
  src/pages/login/assets/Invoice_1401519361.pdf
  src/pages/options/constants.ts
  src/pages/options/create/constants.ts
  src/pages/options/create/create-action.ts
  src/pages/options/create/loader.ts
  src/pages/options/create/options-create-error.element.tsx
  src/pages/options/create/options-create.element.tsx
  src/pages/options/create/routes.tsx
  src/pages/options/create/urls.ts
  src/pages/options/list/constants.tsx
  src/pages/options/list/loader.ts
  src/pages/options/list/options-list-error.element.tsx
  src/pages/options/list/options-list.element.tsx
  src/pages/options/list/routes.tsx
  src/pages/options/list/urls.ts
  src/pages/options/options-error.element.tsx
  src/pages/options/options.element.tsx
  src/pages/options/routes.tsx
  src/pages/options/urls.ts
  src/pages/routes.tsx
  src/pages/tours/create/tours-create.element.tsx
  src/pages/users/create/users-create.element.tsx
  src/types/options/options-list-object.ts
  src/types/selects/questions-object.type.ts
  src/types/selects/tours-object.type.ts
  src/utils/ApiRequestProvider.ts
  src/utils/helpers.tsx
Labels: ready for review

#69 [FEAT-35]: Update Readme
  README.md
Labels: ready for review

#73 60 rf
  src/clean-core/entity/questions/questions.dto.ts
  src/pages/answers/list/routes.tsx
  src/pages/questions/constants.ts
  src/pages/questions/create/constants.ts
  src/pages/questions/create/create-action.ts
  src/pages/questions/create/helpers.tsx
  src/pages/questions/create/loader.ts
  src/pages/questions/create/questions-create.element.tsx
  src/pages/questions/create/routes.tsx
  src/pages/questions/edit/constants.ts
  src/pages/questions/edit/edit-action.ts
  src/pages/questions/edit/loader.ts
  src/pages/questions/edit/questions-edit.element.tsx
  src/pages/questions/edit/routes.tsx
  src/pages/questions/list/constants.tsx
  src/pages/questions/list/loader.ts
  src/pages/questions/list/questions-list.element.tsx
  src/pages/questions/list/routes.tsx
  src/types/questions/questions-list-object.ts
  src/types/selects/survey-object.type.ts
Labels: QA approved, approved

#70 [RF-62]: Refactoring Surveys
  src/constants.ts
  src/pages/requirements/list/constants.tsx
  src/pages/surveys/constants.ts
  src/pages/surveys/create/constants.ts
  src/pages/surveys/create/loader.ts
  src/pages/surveys/create/routes.tsx
  src/pages/surveys/create/surveys-create.element.tsx
  src/pages/surveys/edit/constants.ts
  src/pages/surveys/edit/loader.ts
  src/pages/surveys/edit/routes.tsx
  src/pages/surveys/edit/surveys-edit.element.tsx
  src/pages/surveys/edit/types.ts
  src/pages/surveys/helpers.tsx
  src/pages/surveys/list/constants.tsx
  src/pages/surveys/list/routes.tsx
  src/pages/surveys/list/surveys-list.element.tsx
  src/pages/tours/create/tours-create.element.tsx
  src/types/selects/clients-object.type.ts
  src/types/selects/requirements-list-object.ts
  src/types/surveys/surveys-list-object.ts
Labels: ready for review

#71 [RF-64]: Complete RF for Requirements
  src/clean-core/entity/requirement/requirement.dto.ts
  src/pages/requirements/constants.ts
  src/pages/requirements/create/contants.ts
  src/pages/requirements/create/create-action.ts
  src/pages/requirements/create/loader.ts
  src/pages/requirements/create/requirements-create.element.tsx
  src/pages/requirements/create/routes.tsx
  src/pages/requirements/edit/contants.ts
  src/pages/requirements/edit/edit-action.ts
  src/pages/requirements/edit/helpers.tsx
  src/pages/requirements/edit/loader.ts
  src/pages/requirements/edit/requirements-edit.element.tsx
  src/pages/requirements/edit/routes.tsx
  src/pages/requirements/helpers.tsx
  src/pages/requirements/list/constants.tsx
  src/pages/requirements/list/loader.ts
  src/pages/requirements/list/requirements-list.element.tsx
  src/pages/requirements/list/routes.tsx
  src/pages/requirements/requirements.element.tsx
  src/pages/requirements/routes.tsx
  src/types/requirements/requirement-edit-object.ts
  src/types/selects/requirements-object.type.ts
  src/types/selects/survey-object.type.ts
Labels: ready for review

#75 Feat 74
  assets/icon_launcher.svg
  index.html
  src/clean-core/entity/users/user.dto.ts
  src/components/Icons/FocusIcon.tsx
  src/components/app/navbar/constants.ts
  src/index.css
  src/pages/answers/list/answers-list.element.tsx
  src/pages/answers/list/loader.ts
  src/pages/requirements/list/requirements-list.element.tsx
  src/pages/results/loader.ts
  src/pages/results/results-error.element.tsx
  src/pages/results/results.element.tsx
  src/pages/results/routes.tsx
  src/pages/results/urls.ts
  src/pages/routes.tsx
  src/pages/users/create/create-action.ts
  src/pages/users/create/loader.ts
  src/pages/users/create/routes.tsx
  src/pages/users/create/users-create.element.tsx
  src/pages/users/edit/edit-action.ts
  src/pages/users/edit/loader.ts
  src/pages/users/edit/routes.tsx
  src/pages/users/edit/types.ts
  src/pages/users/edit/users-edit.element.tsx
  src/pages/users/list/constants.tsx
  src/types/selects/clients-object.type.ts
  src/types/users/users-list-object.ts
  tailwind.config.backup.js
  tailwind.config.js
  tsconfig.json
Labels: ready for review
